// Edge function: rewrite resume for JD using Lovable AI Gateway (Gemini 2.5 Pro)
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const SYSTEM_PROMPT = `You are an expert Technical Career Consultant and ATS Optimization Specialist. Your goal is to rewrite a candidate's resume to align with a Job Description (JD) while maintaining professional integrity and authenticity.

CORE PRINCIPLES:
1. STRATEGIC TRANSLATION: Do not simply copy the JD. Instead, "translate" the candidate's existing achievements into the terminology used in the JD. If the JD asks for "Collaborative Development" and the resume says "Worked in a team", rewrite it to focus on "Collaborative Development".
2. NO VERBATIM COPYING: Avoid copy-pasting full sentences or long distinctive phrases from the JD. The resume must sound like it was written by the candidate, not generated by a machine matching keywords.
3. GOOGLE XYZ FORMULA: Every bullet must follow: "Accomplished [X] as measured by [Y], by doing [Z]." Ensure the [Z] part utilizes technical keywords from the JD where appropriate.
4. AUTHENTICITY: Do NOT invent skills, employers, or metrics. If the original resume lacks a metric, use the candidate's description to infer a realistic, conservative achievement.
5. ATS-FRIENDLY FORMATTING: Use a clean, single-column layout. Avoid tables, icons, and complex formatting.
6. KEYWORD CURATION: In the 'skills' section, include only the most relevant technical keywords from the JD that the candidate actually possesses or has demonstrated related experience with. Aim for a curated list of 15-25 high-impact keywords.

Your tone should be professional, concise, and impact-oriented. Focus on hard skills and quantified results.`;

const tool = {
  type: "function",
  function: {
    name: "emit_resume",
    description: "Emit the rewritten ATS-optimized resume and match analysis.",
    parameters: {
      type: "object",
      properties: {
        name: { type: "string" },
        title: { type: "string", description: "Target role title mirrored from JD" },
        contact: {
          type: "object",
          properties: {
            email: { type: "string" },
            phone: { type: "string" },
            location: { type: "string" },
            linkedin: { type: "string" },
            website: { type: "string" },
          },
          required: ["email"],
          additionalProperties: false,
        },
        summary: { type: "string", description: "3-4 line professional summary, JD-aligned but authentic" },
        skills: {
          type: "array",
          items: { type: "string" },
          description: "Curated list of 15-25 high-impact hard skills/tools from the JD matching candidate experience",
        },
        experience: {
          type: "array",
          items: {
            type: "object",
            properties: {
              company: { type: "string" },
              role: { type: "string" },
              location: { type: "string" },
              start: { type: "string" },
              end: { type: "string" },
              bullets: {
                type: "array",
                items: { type: "string" },
                description: "XYZ-formula bullets that translate original experience into JD language.",
              },
            },
            required: ["company", "role", "start", "end", "bullets"],
            additionalProperties: false,
          },
        },
        projects: {
          type: "array",
          items: {
            type: "object",
            properties: {
              name: { type: "string" },
              stack: { type: "string" },
              bullets: { type: "array", items: { type: "string" } },
            },
            required: ["name", "bullets"],
            additionalProperties: false,
          },
        },
        education: {
          type: "array",
          items: {
            type: "object",
            properties: {
              school: { type: "string" },
              degree: { type: "string" },
              start: { type: "string" },
              end: { type: "string" },
              details: { type: "string" },
            },
            required: ["school", "degree"],
            additionalProperties: false,
          },
        },
        certifications: { type: "array", items: { type: "string" } },
        ai_match_score: {
          type: "number",
          description: "AI's qualitative 0-100 score of how well the rewritten resume matches the JD based on REAL experience overlap.",
        },
        jd_keywords: {
          type: "array",
          items: { type: "string" },
          description: "Critical keywords extracted from the JD used in the optimization.",
        },
        company_name: {
          type: "string",
          description: "Company name from JD.",
        },
      },
      required: [
        "name",
        "title",
        "contact",
        "summary",
        "skills",
        "experience",
        "education",
        "ai_match_score",
        "jd_keywords",
        "company_name",
      ],
      additionalProperties: false,
    },
  },
};

// Strip OpenAI-specific keywords ("additionalProperties") so the schema is valid for Gemini.
function cleanSchema(s: any): any {
  if (Array.isArray(s)) return s.map(cleanSchema);
  if (s && typeof s === "object") {
    const out: any = {};
    for (const [k, v] of Object.entries(s)) {
      if (k === "additionalProperties") continue;
      out[k] = cleanSchema(v);
    }
    return out;
  }
  return s;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { resumeText, jobDescription } = await req.json();
    if (!resumeText || !jobDescription) {
      return new Response(JSON.stringify({ error: "resumeText and jobDescription required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
    if (!GEMINI_API_KEY) throw new Error("GEMINI_API_KEY missing");

    const userMsg = `JOB DESCRIPTION:\n"""\n${jobDescription}\n"""\n\nORIGINAL RESUME:\n"""\n${resumeText}\n"""\n\nRewrite the resume to optimize for the JD. Focus on professional alignment and meaningful keyword integration rather than verbatim copying. Use the emit_resume tool.`;

    const MODELS = ["gemini-2.0-flash", "gemini-flash-latest"];
    const delays = [2000, 5000, 12000, 25000];

    const callGemini = (model: string) => fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          systemInstruction: { parts: [{ text: SYSTEM_PROMPT }] },
          contents: [{ role: "user", parts: [{ text: userMsg }] }],
          tools: [
            {
              functionDeclarations: [
                {
                  name: tool.function.name,
                  description: tool.function.description,
                  parameters: cleanSchema(tool.function.parameters),
                },
              ],
            },
          ],
          toolConfig: {
            functionCallingConfig: { mode: "ANY", allowedFunctionNames: ["emit_resume"] },
          },
        }),
      },
    );

    let aiRes: Response | null = null;
    for (const model of MODELS) {
      aiRes = await callGemini(model);
      let attempt = 0;
      while (aiRes.status === 429 && attempt < delays.length) {
        await aiRes.text();
        await new Promise((r) => setTimeout(r, delays[attempt]));
        attempt++;
        aiRes = await callGemini(model);
      }
      if (aiRes.status !== 429) break;
    }

    if (!aiRes || !aiRes.ok) {
      const errText = aiRes ? await aiRes.text() : "Unknown error";
      return new Response(JSON.stringify({ error: `Gemini error: ${errText.slice(0, 300)}` }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const data = await aiRes.json();
    const parts = data?.candidates?.[0]?.content?.parts ?? [];
    const fnCall = parts.find((p: any) => p.functionCall)?.functionCall;
    
    if (!fnCall?.args) {
      return new Response(JSON.stringify({ error: "AI did not return structured resume" }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ resume: fnCall.args }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (e) {
    console.error("rewrite-resume error", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
